#################################
# Personal compilations options #
#################################

$ENV{'TZ'}='America/New_York';

$bibtex_use = 2;
$pdf_mode = 1;
$pdflatex = 'pdflatex --shell-escape -synctex=1 %O %S';
$pdflatex_silent_switch = '-interaction=nonstopmode';

if ( $ENV{'LOCALPAPERBUILD'} ){
  $out_dir = './build';
  $dependents_list = 1;
  $deps_file = './build/deps';
}
